# roles/conscience/tasks/main.yml
---
- name: "Include {{ ansible_distribution }} variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: "Include {{ ansible_distribution }} tasks"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Ensure directories exists
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('openio') }}"
    group: "{{ item.group | default('openio') }}"
    mode: "{{ item.mode | default(0755) }}"
  with_items:
    - path: "/etc/gridinit.d/{{ openio_conscience_namespace }}"
    - path: "{{ openio_conscience_sysconfig_dir }}/{{ openio_conscience_servicename }}"
    - path: "/var/log/oio/sds/{{ openio_conscience_namespace }}/{{ openio_conscience_servicename }}"
      owner: "{{ syslog_user }}"
      mode: "0750"
  tags: install

- name: Generate configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: openio
    group: openio
    mode: 0644
  with_items:
    - src: "conscience.conf.j2"
      dest: "{{ openio_conscience_sysconfig_dir }}/\
        {{ openio_conscience_servicename }}/{{ openio_conscience_servicename }}.conf"
    - src: "services.conf.j2"
      dest: "{{ openio_conscience_sysconfig_dir }}/\
        {{ openio_conscience_servicename }}/{{ openio_conscience_servicename }}-services.conf"
    - src: "policies.conf.j2"
      dest: "{{ openio_conscience_sysconfig_dir }}/\
        {{ openio_conscience_servicename }}/{{ openio_conscience_servicename }}-policies.conf"
    - src: "gridinit_conscience.conf.j2"
      dest: "{{ openio_conscience_gridinit_dir }}/{{ openio_conscience_gridinit_file_prefix }}\
        {{ openio_conscience_servicename }}.conf"
  register: _conscience_conf

- name: restart conscience
  shell: |
    gridinit_cmd reload
    gridinit_cmd restart {{ openio_conscience_namespace }}-{{ openio_conscience_servicename }}
  when:
    - _conscience_conf.changed
    - not openio_conscience_provision_only
  tags: configure

...
