# roles/conscience/tasks/main.yml
---
- name: "Include {{ ansible_distribution }} variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: "Include {{ ansible_distribution }} tasks"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Ensure directories exists
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('openio') }}"
    group: "{{ item.group | default('openio') }}"
    mode: "{{ item.mode | default(0755) }}"
  with_items:
    - path: "/etc/gridinit.d/{{ openio_conscience_namespace }}"
    - path: "{{ openio_conscience_sysconfig_dir }}/{{ openio_conscience_servicename }}"
    - path: "/var/log/oio/sds/{{ openio_conscience_namespace }}/{{ openio_conscience_servicename }}"
      owner: "{{ syslog_user }}"
      mode: "0750"
  tags: install

- name: Generate configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: openio
    group: openio
    mode: 0644
  with_items:
    - src: "conscience.conf.j2"
      dest: "{{ openio_conscience_sysconfig_dir }}/\
        {{ openio_conscience_servicename }}/{{ openio_conscience_servicename }}.conf"
    - src: "services.conf.j2"
      dest: "{{ openio_conscience_sysconfig_dir }}/\
        {{ openio_conscience_servicename }}/{{ openio_conscience_servicename }}-services.conf"
    - src: "policies.conf.j2"
      dest: "{{ openio_conscience_sysconfig_dir }}/\
        {{ openio_conscience_servicename }}/{{ openio_conscience_servicename }}-policies.conf"
    - src: "gridinit_conscience.conf.j2"
      dest: "{{ openio_conscience_gridinit_dir }}/{{ openio_conscience_gridinit_file_prefix }}\
        {{ openio_conscience_servicename }}.conf"
  register: _conscience_conf

- name: "restart conscience to apply the new configuration"
  shell: |
    gridinit_cmd reload
    gridinit_cmd restart {{ openio_conscience_namespace }}-{{ openio_conscience_servicename }}
  register: _restart_conscience
  when:
    - _conscience_conf is changed
    - not openio_conscience_provision_only
  tags: configure

- block:
    - name: "Ensure conscience is started"
      command: gridinit_cmd start {{ openio_conscience_namespace }}-{{ openio_conscience_servicename }}
      register: _start_conscience
      changed_when: '"Success" in _start_conscience.stdout'
      when:
        - not openio_conscience_provision_only
        - _restart_conscience is skipped
      tags: configure

    - name: check conscience
      command: "oio-tool ping {{ openio_conscience_bind_address }}:{{ openio_conscience_bind_port }}"
      register: _conscience_check
      retries: 3
      delay: 5
      until: _conscience_check is success
      changed_when: false
      failed_when:
        - _conscience_check.rc != 0
        - "'PING OK' not in _conscience_check.stdout"
  when: openio_bootstrap | d(false)
...
