---
- name: generate conscience group
  hosts: all
  gather_facts: false
  tasks:
    - add_host:
        name: "{{ item.name }}"
        ansible_host: "{{ item.openio_bind_address }}"
        openio_bind_address: "{{ item.openio_bind_address }}"
        groups: conscience
      with_items:
        - { name: "localhost", openio_bind_address: "172.17.0.2" }
        - { name: "node2", openio_bind_address: "172.17.0.3" }
        - { name: "node3", openio_bind_address: "172.17.0.4" }
      delegate_to: localhost
      run_once: true
      changed_when: false

- hosts: localhost
  become: true
  vars:
    NS: TRAVIS
    openio_bootstrap: true
  roles:
    - role: repository
      openio_repository_no_log: false
      openio_repository_mirror_host: mirror2.openio.io
    - role: users
    - role: namespace
      openio_namespace_name: "{{ NS }}"
    - role: gridinit
      #openio_gridinit_per_ns: true
      openio_gridinit_namespace: "{{ NS }}"
    - role: meta
      openio_meta_namespace: "{{ NS }}"
    - role: conscienceagent
      openio_conscienceagent_namespace: "{{ NS }}"
    - role: oioproxy
      openio_oioproxy_namespace: "{{ NS }}"
    - role: role_under_test
      openio_conscience_namespace: "{{ NS }}"
      openio_conscience_bind_address: "{{ ansible_default_ipv4.address }}"
      openio_conscience_pools:
        - name: rawx21
          targets:
            - slot: rawx-europe
              fallback: rawx
              count: 2
            - slot: rawx-asia
              fallback: rawx
              count: 1
          min_dist: 2
      openio_conscience_multiple_enable: true

...
